/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package vista;

/**
 *
 * @author Martin
 */
public class ProntuarioAspirante extends javax.swing.JFrame {

    /** Creates new form ProntuarioAspirante */
    public ProntuarioAspirante() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        txtboxNombre = new javax.swing.JTextField();
        txtBoxApellido = new javax.swing.JTextField();
        txtBoxNacionalidad = new javax.swing.JTextField();
        txtBoxLocalidad = new javax.swing.JTextField();
        txtBoxProvincia = new javax.swing.JTextField();
        txtBoxEstadoCivil = new javax.swing.JTextField();
        txtBoxPaisOrigen = new javax.swing.JTextField();
        txtBoxApyNomEsposa = new javax.swing.JTextField();
        txtBoxApyNomMadre = new javax.swing.JTextField();
        txtBoxApyNomPadre = new javax.swing.JTextField();
        txtBoxDomicilioLab = new javax.swing.JTextField();
        txtBoxLocalidadLab = new javax.swing.JTextField();
        txtBoxDni = new javax.swing.JTextField();
        txtBoxExpedido = new javax.swing.JTextField();
        txtBoxProfesion = new javax.swing.JTextField();
        txtBoxInstruccion = new javax.swing.JTextField();
        txtBoxLocalidadAct = new javax.swing.JTextField();
        txtBoxTelefono = new javax.swing.JTextField();
        txtBoxProvinciaAct = new javax.swing.JTextField();
        txtBoxDomicilioActual = new javax.swing.JTextField();
        btnGenerar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        rbtnHombre = new javax.swing.JRadioButton();
        rbtnMujer = new javax.swing.JRadioButton();
        dtpkrFechaNacimiento = new rojeru_san.componentes.RSDateChooser();
        btnLimpiar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtBoxSangre = new javax.swing.JTextField();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtboxNombre.setText("Nombre");

        txtBoxApellido.setText("Apellido");
        txtBoxApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBoxApellidoActionPerformed(evt);
            }
        });

        txtBoxNacionalidad.setText("Nacionalidad");

        txtBoxLocalidad.setText("Localidad");

        txtBoxProvincia.setText("Provincia");

        txtBoxEstadoCivil.setText("Estado Civil");

        txtBoxPaisOrigen.setText("Pais Origen");

        txtBoxApyNomEsposa.setText("Nombre y Apellido Esposa");

        txtBoxApyNomMadre.setText("Nombre y Apellido Madre");

        txtBoxApyNomPadre.setText("Nombre y Apellido Padre");

        txtBoxDomicilioLab.setText("Domicilio Laboral");

        txtBoxLocalidadLab.setText("Localidad Laboral");

        txtBoxDni.setText("Documento Identidad");

        txtBoxExpedido.setText("Expedido Por");

        txtBoxProfesion.setText("Profesion");

        txtBoxInstruccion.setText("Instruccion");

        txtBoxLocalidadAct.setText("Localidad Actual");
        txtBoxLocalidadAct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBoxLocalidadActActionPerformed(evt);
            }
        });

        txtBoxTelefono.setText("Telefono");
        txtBoxTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBoxTelefonoActionPerformed(evt);
            }
        });

        txtBoxProvinciaAct.setText("Provincia Actual");

        txtBoxDomicilioActual.setText("Domicilio Actual");

        btnGenerar.setText("Generar");

        btnSalir.setText("Salir");

        buttonGroup1.add(rbtnHombre);
        rbtnHombre.setSelected(true);
        rbtnHombre.setText("Hombre");

        buttonGroup1.add(rbtnMujer);
        rbtnMujer.setText("Mujer");
        rbtnMujer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnMujerActionPerformed(evt);
            }
        });

        dtpkrFechaNacimiento.setColorBackground(new java.awt.Color(0, 0, 0));
        dtpkrFechaNacimiento.setColorButtonHover(new java.awt.Color(0, 0, 0));
        dtpkrFechaNacimiento.setColorDiaActual(new java.awt.Color(0, 0, 0));
        dtpkrFechaNacimiento.setColorForeground(new java.awt.Color(0, 0, 0));
        dtpkrFechaNacimiento.setPlaceholder("Fecha Nacimiento");

        btnLimpiar.setText("Limpiar");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("PRONTUARIO ASPIRANTE");

        txtBoxSangre.setText("Sangre");
        txtBoxSangre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBoxSangreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtboxNombre)
                                .addComponent(txtBoxApellido)
                                .addComponent(txtBoxPaisOrigen)
                                .addComponent(txtBoxProvincia)
                                .addComponent(txtBoxLocalidad)
                                .addComponent(txtBoxEstadoCivil)
                                .addComponent(txtBoxApyNomEsposa)
                                .addComponent(txtBoxApyNomMadre)
                                .addComponent(txtBoxApyNomPadre)
                                .addComponent(txtBoxNacionalidad)
                                .addComponent(dtpkrFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(btnGenerar)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                                    .addComponent(btnLimpiar)))
                            .addComponent(txtBoxSangre, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(rbtnHombre)
                                .addComponent(rbtnMujer)
                                .addComponent(txtBoxDni, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                                .addComponent(txtBoxExpedido)
                                .addComponent(txtBoxProfesion)
                                .addComponent(txtBoxInstruccion)
                                .addComponent(txtBoxDomicilioActual)
                                .addComponent(txtBoxLocalidadAct)
                                .addComponent(txtBoxProvinciaAct)
                                .addComponent(txtBoxDomicilioLab)
                                .addComponent(txtBoxLocalidadLab))
                            .addComponent(btnSalir, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtBoxTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtboxNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbtnHombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtBoxApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbtnMujer, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtBoxNacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBoxTelefono, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(dtpkrFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBoxPaisOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBoxProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBoxLocalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBoxSangre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBoxEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBoxApyNomEsposa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBoxApyNomMadre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBoxApyNomPadre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtBoxDni, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBoxExpedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBoxProfesion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBoxInstruccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBoxDomicilioActual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBoxLocalidadAct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBoxProvinciaAct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBoxDomicilioLab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBoxLocalidadLab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGenerar)
                    .addComponent(btnSalir)
                    .addComponent(btnLimpiar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBoxApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBoxApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBoxApellidoActionPerformed

    private void txtBoxLocalidadActActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBoxLocalidadActActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBoxLocalidadActActionPerformed

    private void rbtnMujerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnMujerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnMujerActionPerformed

    private void txtBoxTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBoxTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBoxTelefonoActionPerformed

    private void txtBoxSangreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBoxSangreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBoxSangreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProntuarioAspirante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProntuarioAspirante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProntuarioAspirante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProntuarioAspirante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProntuarioAspirante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnGenerar;
    public javax.swing.JButton btnLimpiar;
    public javax.swing.JButton btnSalir;
    private javax.swing.ButtonGroup buttonGroup1;
    public rojeru_san.componentes.RSDateChooser dtpkrFechaNacimiento;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    public javax.swing.JRadioButton rbtnHombre;
    public javax.swing.JRadioButton rbtnMujer;
    public javax.swing.JTextField txtBoxApellido;
    public javax.swing.JTextField txtBoxApyNomEsposa;
    public javax.swing.JTextField txtBoxApyNomMadre;
    public javax.swing.JTextField txtBoxApyNomPadre;
    public javax.swing.JTextField txtBoxDni;
    public javax.swing.JTextField txtBoxDomicilioActual;
    public javax.swing.JTextField txtBoxDomicilioLab;
    public javax.swing.JTextField txtBoxEstadoCivil;
    public javax.swing.JTextField txtBoxExpedido;
    public javax.swing.JTextField txtBoxInstruccion;
    public javax.swing.JTextField txtBoxLocalidad;
    public javax.swing.JTextField txtBoxLocalidadAct;
    public javax.swing.JTextField txtBoxLocalidadLab;
    public javax.swing.JTextField txtBoxNacionalidad;
    public javax.swing.JTextField txtBoxPaisOrigen;
    public javax.swing.JTextField txtBoxProfesion;
    public javax.swing.JTextField txtBoxProvincia;
    public javax.swing.JTextField txtBoxProvinciaAct;
    public javax.swing.JTextField txtBoxSangre;
    public javax.swing.JTextField txtBoxTelefono;
    public javax.swing.JTextField txtboxNombre;
    // End of variables declaration//GEN-END:variables

}
